import { useMemo, useState } from "react";
import { Link, NavLink, Route, Routes, useNavigate } from "react-router-dom";
import { Activity, AlertTriangle, ArrowRight, Bell, Building2, CalendarDays, CheckCircle2, DoorOpen, Home, LogOut, Map, MapPin, Menu, QrCode, Search, ShieldCheck, UserRound, Wifi, Wrench, X } from "lucide-react";
import { useAuth } from "../auth/useAuth";

const studentRooms = [
  { id: "CSE-102", building: "CSE Building", floor: 1, type: "Computer Lab", capacity: 30, availability: "Available" },
  { id: "CSE-202", building: "CSE Building", floor: 2, type: "Seminar Hall", capacity: 120, availability: "Available" },
  { id: "MECH-101", building: "Mechanical Block", floor: 1, type: "Project Lab", capacity: 42, availability: "Occupied" },
  { id: "ADMIN-201", building: "Admin Block", floor: 2, type: "Conference Room", capacity: 30, availability: "Available" },
  { id: "LIB-201", building: "Central Library", floor: 2, type: "Reading Room", capacity: 60, availability: "Unavailable" },
  { id: "CSE-301", building: "CSE Building", floor: 3, type: "Classroom", capacity: 60, availability: "Occupied" },
];
const sampleNotices = [
  { title: "Annual Tech Fest registrations are open", category: "Events", date: "Today · 10:30 AM", detail: "Register through the student portal before 18 October." },
  { title: "Library hours extended during examinations", category: "Campus notice", date: "Yesterday", detail: "The Central Library will remain open until 10:00 PM this week." },
  { title: "Scheduled power maintenance", category: "Important", date: "5 Oct 2026", detail: "Brief power interruptions are expected in the Mechanical Block on Friday." },
];
const studentNav = [
  { title: "CAMPUS", items: [["Dashboard", "/student", Home], ["Digital Twin / Campus Map", "/student/map", Map], ["Find a Room", "/student/find-room", Search], ["Room Availability", "/student/availability", DoorOpen], ["Bookings", "/student/bookings", CalendarDays]] },
  { title: "SERVICES", items: [["Report Maintenance", "/student/report", QrCode], ["My Requests", "/student/requests", Wrench], ["Notices", "/student/notices", Bell], ["Emergency", "/student/emergency", AlertTriangle]] },
  { title: "ACCOUNT", items: [["Profile", "/student/profile", UserRound]] },
];

function StudentPortal() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const [requests, setRequests] = useState(() => { try { return JSON.parse(localStorage.getItem("campus-student-requests") || "[]"); } catch { return []; } });
  const [bookings, setBookings] = useState(() => { try { return JSON.parse(localStorage.getItem("campus-student-bookings") || "[]"); } catch { return []; } });
  const [search, setSearch] = useState("");
  const [identified, setIdentified] = useState(false);
  const [notice, setNotice] = useState("");
  const [mobileOpen, setMobileOpen] = useState(false);

  function signOut() { logout(); navigate("/login", { replace: true }); }
  function addBooking(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const item = { id: `BK-${String(bookings.length + 1).padStart(3, "0")}`, room: form.get("room"), date: form.get("date"), time: form.get("time"), purpose: form.get("purpose"), status: "Confirmed" }; const next = [item, ...bookings]; setBookings(next); localStorage.setItem("campus-student-bookings", JSON.stringify(next)); setNotice(`Booking ${item.id} confirmed for ${item.room}.`); }
  function addRequest(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const item = { id: `MNT-S${String(requests.length + 1).padStart(3, "0")}`, location: identified ? "CSE-204 · Computer Lab 2" : String(form.get("location")), equipment: identified ? "Projector #02" : String(form.get("equipment") || "Room asset"), issue: String(form.get("description")), priority: String(form.get("priority")), date: new Date().toLocaleString(), status: "Pending" }; const next = [item, ...requests]; setRequests(next); localStorage.setItem("campus-student-requests", JSON.stringify(next)); setNotice(`Maintenance request ${item.id} submitted successfully.`); setIdentified(false); event.currentTarget.reset(); }
  const matchingRooms = useMemo(() => studentRooms.filter((room) => `${room.id} ${room.building} ${room.type}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const studentName = user?.name || "Student";

  return <div className="student-app">
    <aside className={`student-sidebar ${mobileOpen ? "open" : ""}`}><div className="student-brand"><div className="logo-icon"><Wifi size={21}/></div><div><strong>SMART CAMPUS</strong><small>Student Portal</small></div><button className="student-mobile-close" onClick={() => setMobileOpen(false)}><X size={19}/></button></div><nav>{studentNav.map((group) => <div className="student-nav-group" key={group.title}><span>{group.title}</span>{group.items.map(([label, path, Icon]) => <NavLink key={path} to={path} end={path === "/student"} onClick={() => setMobileOpen(false)} className={({ isActive }) => `student-nav-link ${isActive ? "active" : ""}`}><Icon size={17}/>{label}</NavLink>)}</div>)}</nav><button className="student-signout" onClick={signOut}><LogOut size={17}/>Sign out</button></aside>
    {mobileOpen && <button className="student-sidebar-scrim" onClick={() => setMobileOpen(false)} aria-label="Close navigation"/>}
    <div className="student-main"><header className="student-topbar"><button className="student-menu-button" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={19}/></button><div className="student-college"><strong>Walchand College of Engineering</strong><small>Sangli, Maharashtra</small></div><div className="student-search"><Search size={17}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search buildings, rooms..."/><kbd>⌘K</kbd></div><div className="student-live"><i/>Live<small>Campus connected</small></div><button className="student-user" onClick={() => navigate("/student/profile")}><span>{studentName.slice(0, 1).toUpperCase()}</span>{studentName}</button><button className="student-logout-icon" title="Sign out" onClick={signOut}><LogOut size={17}/></button></header>
      <main className="student-content">{notice && <div className="student-toast"><CheckCircle2 size={17}/>{notice}<button onClick={() => setNotice("")}><X size={15}/></button></div>}
        <Routes>
          <Route index element={<StudentHome name={studentName} requests={requests} bookings={bookings} rooms={matchingRooms} onReport={() => { setIdentified(false); navigate("/student/report"); }} onBook={() => navigate("/student/bookings")} onNotices={() => navigate("/student/notices")}/>} />
          <Route path="map" element={<CampusMap rooms={matchingRooms}/>} />
          <Route path="find-room" element={<RoomDirectory rooms={matchingRooms} search={search}/>} />
          <Route path="availability" element={<Availability rooms={matchingRooms}/>} />
          <Route path="bookings" element={<Bookings rooms={studentRooms} bookings={bookings} onSubmit={addBooking}/>} />
          <Route path="report" element={<MaintenanceReport identified={identified} onIdentify={() => setIdentified(true)} onSubmit={addRequest}/>} />
          <Route path="requests" element={<MyRequests requests={requests}/>} />
          <Route path="notices" element={<Notices/>} />
          <Route path="emergency" element={<EmergencyInfo/>} />
          <Route path="profile" element={<Profile name={studentName} email={user?.email}/>} />
          <Route path="*" element={<StudentHome name={studentName} requests={requests} bookings={bookings} rooms={matchingRooms} onReport={() => navigate("/student/report")} onBook={() => navigate("/student/bookings")} onNotices={() => navigate("/student/notices")}/>} />
        </Routes>
      </main>
    </div>
  </div>;
}

function PageHeading({ title, description, action }) { return <header className="student-page-heading"><div><h1>{title}</h1><p>{description}</p></div>{action}</header>; }
function StudentHome({ name, requests, bookings, rooms, onReport, onBook, onNotices }) {
  const date = new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date());
  return <><PageHeading title={`Welcome back, ${name}`} description={`${date} · Campus systems are operating normally.`} action={<span className="student-date-tag"><Activity size={15}/> Campus status: Normal</span>}/><section className="student-quick-grid"><QuickCard icon={Search} title="Find a Room" detail="Search campus spaces" to="/student/find-room"/><QuickCard icon={DoorOpen} title="Room Availability" detail="Check live room status" to="/student/availability"/><button className="student-quick-card" onClick={onBook}><CalendarDays/><strong>Book a Room</strong><small>Reserve campus spaces</small><ArrowRight/></button><button className="student-quick-card" onClick={onReport}><QrCode/><strong>Report Maintenance</strong><small>Scan QR or report an issue</small><ArrowRight/></button><QuickCard icon={Wrench} title="My Requests" detail={`${requests.length} requests submitted`} to="/student/requests"/><button className="student-quick-card" onClick={onNotices}><Bell/><strong>Notices</strong><small>Campus news and events</small><ArrowRight/></button></section><section className="student-home-grid"><div className="student-panel student-map-panel"><header><div><h2>Campus Digital Twin</h2><p>Explore buildings and find campus spaces</p></div><Link to="/student/map">Open campus map <ArrowRight size={14}/></Link></header><CampusMapArt/><div className="student-building-list"><span><i className="normal"/>CSE Building</span><span><i className="warning"/>Mechanical Block</span><span><i className="normal"/>Central Library</span><span><i className="normal"/>Admin Block</span></div></div><div className="student-panel student-availability-panel"><header><div><h2>Room Availability</h2><p>Live campus spaces</p></div><Link to="/student/availability">View all</Link></header><div className="student-room-counts"><div><strong>24</strong><span>Available</span></div><div><strong>18</strong><span>Occupied</span></div><div><strong>3</strong><span>Unavailable</span></div></div><div className="student-recent-list"><h3>Quick availability</h3>{rooms.slice(0, 3).map((room) => <RoomLine room={room} key={room.id}/>)}</div></div></section><section className="student-home-bottom"><div className="student-panel"><header><div><h2>My upcoming bookings</h2><p>Room reservations</p></div><Link to="/student/bookings">Manage bookings</Link></header>{bookings.length ? bookings.slice(0, 3).map((item) => <BookingLine key={item.id} item={item}/>) : <div className="student-empty-inline"><CalendarDays size={19}/>You have no upcoming bookings yet.</div>}</div><div className="student-panel"><header><div><h2>Campus notices</h2><p>Latest announcements</p></div><Link to="/student/notices">All notices</Link></header>{sampleNotices.slice(0, 2).map((item) => <article className="student-notice-line" key={item.title}><span className="notice-dot"/><div><strong>{item.title}</strong><small>{item.category} · {item.date}</small></div></article>)}</div></section></>;
}
function QuickCard({ icon: Icon, title, detail, to }) { return <Link className="student-quick-card" to={to}><Icon/><strong>{title}</strong><small>{detail}</small><ArrowRight/></Link>; }
function CampusMapArt() { return <div className="student-campus-map"><div className="student-map-road road-a"/><div className="student-map-road road-b"/><div className="student-map-building cse"><Building2/><span>CSE Building</span></div><div className="student-map-building mech"><Building2/><span>Mechanical</span></div><div className="student-map-building library"><Building2/><span>Library</span></div><div className="student-map-building admin"><Building2/><span>Admin Block</span></div><span className="student-map-pin"><MapPin size={16}/></span></div>; }
function RoomLine({ room }) { return <div className="student-room-line"><span><strong>{room.id}</strong><small>{room.type} · Capacity {room.capacity}</small></span><em className={`room-state ${room.availability.toLowerCase()}`}>{room.availability}</em></div>; }
function CampusMap({ rooms }) { return <><PageHeading title="Campus Digital Twin" description="Explore campus buildings, floors and room status."/><section className="student-panel student-full-map"><CampusMapArt/><div className="student-building-list"><span><i className="normal"/>CSE Building</span><span><i className="warning"/>Mechanical Block</span><span><i className="normal"/>Central Library</span><span><i className="normal"/>Admin Block</span></div></section><section className="student-panel student-room-directory"><header><div><h2>Rooms on campus</h2><p>Availability linked to the campus map</p></div></header><div className="student-room-grid">{rooms.map((room) => <RoomCard room={room} key={room.id}/>)}</div></section></>; }
function RoomDirectory({ rooms, search }) { return <><PageHeading title="Find a Room" description="Search campus rooms by building, type, or room number."/><div className="student-search-inline"><Search size={17}/><span>{search || "Use the search field above to filter campus rooms"}</span></div><section className="student-room-grid">{rooms.map((room) => <RoomCard room={room} key={room.id}/>)}</section></>; }
function Availability({ rooms }) { return <><PageHeading title="Room Availability" description="Check occupied, available, and temporarily unavailable campus spaces."/><section className="student-availability-summary"><div><strong>24</strong><span>Available rooms</span></div><div><strong>18</strong><span>Occupied now</span></div><div><strong>3</strong><span>Unavailable</span></div><div><strong>1,240</strong><span>Total capacity</span></div></section><section className="student-panel student-room-directory"><header><div><h2>Live room status</h2><p>Room capacity and availability across campus</p></div><span className="student-live"><i/>Updated just now</span></header><div className="student-room-grid">{rooms.map((room) => <RoomCard room={room} key={room.id}/>)}</div></section></>; }
function RoomCard({ room }) { return <article className="student-room-card"><div><span className="student-room-icon"><DoorOpen size={18}/></span><em className={`room-state ${room.availability.toLowerCase()}`}>{room.availability}</em></div><strong>{room.id}</strong><span>{room.building} · Floor {room.floor}</span><small>{room.type} · Capacity {room.capacity}</small></article>; }
function Bookings({ rooms, bookings, onSubmit }) { return <><PageHeading title="Room Bookings" description="Reserve a campus room for your academic activities."/><section className="student-panel student-booking-panel"><header><div><h2>Book a room</h2><p>Select a room and time to check availability</p></div></header><form className="student-form-grid" onSubmit={onSubmit}><label>Room<select name="room" required>{rooms.filter((room) => room.availability === "Available").map((room) => <option value={room.id} key={room.id}>{room.id} · {room.building} · Capacity {room.capacity}</option>)}</select></label><label>Date<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0, 10)}/></label><label>Time<select name="time"><option>09:00–11:00</option><option>11:00–13:00</option><option>14:00–16:00</option><option>16:00–18:00</option></select></label><label>Purpose<input name="purpose" required placeholder="e.g. Project group meeting"/></label><button type="submit">Check Availability & Book <ArrowRight size={16}/></button></form></section><section className="student-panel student-room-directory"><header><div><h2>My bookings</h2><p>Your room reservations</p></div></header>{bookings.length ? bookings.map((item) => <BookingLine key={item.id} item={item}/>) : <div className="student-empty-inline"><CalendarDays size={19}/>No bookings yet. Reserve a room above.</div>}</section></>; }
function BookingLine({ item }) { return <article className="student-booking-line"><CalendarDays size={17}/><div><strong>{item.room} <small>{item.id}</small></strong><span>{item.date} · {item.time} · {item.purpose}</span></div><em>{item.status}</em></article>; }
function MaintenanceReport({ identified, onIdentify, onSubmit }) { return <><PageHeading title="Report Maintenance" description="Scan a room or equipment QR code, then tell the campus team what needs attention." action={<span className="student-date-tag"><QrCode size={15}/> QR-based report</span>}/><section className="student-panel student-report-panel"><header><div><h2><QrCode size={18}/> QR Maintenance</h2><p>Connect your report to the matching Digital Twin asset.</p></div></header>{!identified ? <div className="student-qr-prompt"><span><QrCode size={40}/></span><div><strong>Identify the room or equipment</strong><p>Scan the QR code attached to the physical asset. You can also enter the asset code manually.</p></div><button onClick={onIdentify}><QrCode size={16}/> Scan QR Code</button><label>Enter QR ID<input placeholder="QR-CSE-204-P02" onChange={(event) => { if (event.target.value.trim().toUpperCase() === "QR-CSE-204-P02") onIdentify(); }}/></label></div> : <form className="student-maintenance-form" onSubmit={onSubmit}><div className="student-identified-asset"><CheckCircle2 size={18}/><div><strong>QR code successfully identified</strong><span>CSE Department · Floor 2 · Computer Lab 2 · Projector #02</span></div><button type="button" onClick={onIdentify}>Change</button></div><div className="student-readonly-location"><label>Location<input readOnly value="CSE-204 · Computer Lab 2"/></label><label>Equipment<input readOnly value="Projector #02"/></label></div><label>Issue category<select name="category" defaultValue="Equipment"><option>Electrical</option><option>Furniture</option><option>Network</option><option>Equipment</option><option>Cleanliness</option><option>Other</option></select></label><label>Describe the issue<textarea name="description" required rows="3" placeholder="What happened? A short description is enough."/></label><div className="student-readonly-location"><label>Priority<select name="priority"><option>Low</option><option selected>Medium</option><option>High</option></select></label><label>Optional photo<input name="image" type="file" accept="image/*"/></label></div><button className="student-submit" type="submit">Submit Maintenance Report <ArrowRight size={16}/></button></form>}</section></>; }
function MyRequests({ requests }) { return <><PageHeading title="My Requests" description="Track maintenance issues you have reported."/><section className="student-panel student-requests-panel"><header><div><h2>Maintenance requests</h2><p>Status updates from campus maintenance</p></div><span>{requests.length} requests</span></header>{requests.length ? requests.map((item) => <article className="student-request-line" key={item.id}><div className="student-request-icon"><Wrench size={17}/></div><div><strong>{item.issue}</strong><span>{item.location} · {item.equipment}</span><small>{item.id} · {item.date}</small></div><em className={`request-state ${item.status.toLowerCase().replaceAll(" ", "-")}`}>{item.status}</em></article>) : <div className="student-empty-inline"><Wrench size={19}/>Your submitted maintenance reports will appear here.</div>}</section></>; }
function Notices() { return <><PageHeading title="Notices & Alerts" description="College announcements, events and important updates."/>{sampleNotices.map((item) => <article className="student-panel student-notice-card" key={item.title}><span>{item.category}</span><h2>{item.title}</h2><small>{item.date}</small><p>{item.detail}</p></article>)}</>; }
function EmergencyInfo() { return <><PageHeading title="Emergency Information" description="Campus contacts and guidance for urgent situations."/><section className="student-emergency-banner"><AlertTriangle size={22}/><div><strong>For immediate danger, call campus security.</strong><span>Campus emergency support is available 24 hours a day.</span></div><a href="tel:02332623043">Call Security</a></section><section className="student-emergency-grid"><article><ShieldCheck/><strong>Campus Security</strong><span>Emergency response and campus safety</span><b>0233 262 3043</b></article><article><Wrench/><strong>Facilities Desk</strong><span>Urgent building and utility issues</span><b>0233 262 3100</b></article></section></>; }
function Profile({ name, email }) { const { logout } = useAuth(); const navigate = useNavigate(); return <><PageHeading title="My Profile" description="Your student account and campus access."/><section className="student-panel student-profile-card"><div className="student-profile-avatar">{name.slice(0, 1).toUpperCase()}</div><div><h2>{name}</h2><p>{email}</p><span>STUDENT · Walchand College of Engineering</span></div><button onClick={() => { logout(); navigate("/login", { replace: true }); }}><LogOut size={16}/> Sign out</button></section><section className="student-panel student-profile-details"><header><h2>Account access</h2></header><p><CheckCircle2/> Student services available: campus map, room search, bookings, maintenance reports and notices.</p></section></>; }

export default StudentPortal;
